monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - account     # Custom channel for account-related logs
        - transfer    # Custom channel for transfer-related logs

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            account:
                type: stream
                path: "%kernel.logs_dir%/account.log"
                level: debug
                channels: ["account"]
            transfer:
                type: stream
                path: "%kernel.logs_dir%/transfer.log"
                level: debug
                channels: ["transfer"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            account:
                type: stream
                path: "%kernel.logs_dir%/account_test.log"
                level: debug
                channels: ["account"]
            transfer:
                type: stream
                path: "%kernel.logs_dir%/transfer_test.log"
                level: debug
                channels: ["transfer"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!deprecation"]
                buffer_size: 50 # Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
            account:
                type: stream
                path: "%kernel.logs_dir%/account.log"
                level: info
                channels: ["account"]
            transfer:
                type: stream
                path: "%kernel.logs_dir%/transfer.log"
                level: info
                channels: ["transfer"]
